"""Log existing model artifacts to MLflow and create registry-style docs.

Run from the project root:
    python src/models/mlflow_tracking.py

This script does not train or retrain a model. It reads existing saved metrics
and artifacts, logs them to MLflow when MLflow is installed, and always writes
portfolio-friendly model registry documentation under reports/.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


REPORTS_DIR = Path("reports")
MODEL_PATH = Path("models/credit_risk_model.pkl")
METRICS_PATH = REPORTS_DIR / "final_model_metrics.json"
MLFLOW_SUMMARY_PATH = REPORTS_DIR / "mlflow_experiment_summary.md"
REGISTRY_JSON_PATH = REPORTS_DIR / "model_registry.json"
REGISTRY_MD_PATH = REPORTS_DIR / "model_registry.md"
MLFLOW_TRACKING_URI = "sqlite:///mlruns/mlflow.db"
EXPERIMENT_NAME = "FinSight Credit Risk"
RUN_NAME = "final_lightgbm_existing_artifacts"

ARTIFACT_PATHS = [
    REPORTS_DIR / "final_model_report.md",
    REPORTS_DIR / "final_model_metrics.json",
    REPORTS_DIR / "cross_validation_summary.md",
    REPORTS_DIR / "calibration_report.md",
    REPORTS_DIR / "business_impact_summary.md",
    REPORTS_DIR / "explainability_summary.md",
    REPORTS_DIR / "fairness_proxy_analysis.md",
    REPORTS_DIR / "leakage_audit.md",
    REPORTS_DIR / "model_card.md",
]


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments."""
    parser = argparse.ArgumentParser(
        description="Log existing FinSight model artifacts to MLflow."
    )
    parser.add_argument(
        "--tracking-uri",
        default=MLFLOW_TRACKING_URI,
        help=(
            "MLflow tracking URI. Defaults to local SQLite store "
            "sqlite:///mlruns/mlflow.db."
        ),
    )
    parser.add_argument(
        "--experiment-name",
        default=EXPERIMENT_NAME,
        help="MLflow experiment name.",
    )
    parser.add_argument(
        "--run-name",
        default=RUN_NAME,
        help="MLflow run name.",
    )
    parser.add_argument(
        "--skip-mlflow",
        action="store_true",
        help="Only write registry documentation; do not attempt MLflow logging.",
    )
    return parser.parse_args()


def load_metrics() -> dict[str, Any]:
    """Load final model metrics generated by train_final_model.py."""
    if not METRICS_PATH.exists():
        raise FileNotFoundError(
            "Missing reports/final_model_metrics.json. "
            "Run python src/models/train_final_model.py first."
        )
    return json.loads(METRICS_PATH.read_text(encoding="utf-8"))


def flatten_metrics(metrics: dict[str, Any]) -> dict[str, float]:
    """Flatten validation/test metrics for MLflow logging."""
    flattened: dict[str, float] = {}
    for split_name, split_payload in metrics.get("splits", {}).items():
        classification = split_payload.get("classification", {})
        calibration = split_payload.get("calibration", {})
        for metric_name, value in classification.items():
            if isinstance(value, (int, float)):
                flattened[f"{split_name}_{metric_name}"] = float(value)
        brier_score = calibration.get("brier_score")
        if isinstance(brier_score, (int, float)):
            flattened[f"{split_name}_brier_score"] = float(brier_score)
    return flattened


def registry_entry(metrics: dict[str, Any], mlflow_status: dict[str, Any]) -> dict[str, Any]:
    """Build a model registry-style metadata record from existing artifacts."""
    return {
        "model_name": "FinSight Credit Risk LightGBM",
        "model_version": "0.13.0",
        "model_stage": "portfolio_ready_not_production_approved",
        "model_type": metrics.get("model_type", "unknown"),
        "selection_metric": metrics.get("selection_metric", "unknown"),
        "threshold_strategy": metrics.get("threshold_strategy", "unknown"),
        "threshold": metrics.get("threshold"),
        "top_k": metrics.get("top_k"),
        "random_state": metrics.get("random_state"),
        "rows_loaded": metrics.get("rows_loaded"),
        "feature_count": metrics.get("feature_count"),
        "artifact_path": MODEL_PATH.as_posix(),
        "metrics_path": METRICS_PATH.as_posix(),
        "created_utc": datetime.now(timezone.utc).isoformat(),
        "mlflow": mlflow_status,
        "validation_metrics": metrics.get("splits", {})
        .get("validation", {})
        .get("classification", {}),
        "test_metrics": metrics.get("splits", {}).get("test", {}).get("classification", {}),
        "governance": {
            "model_card": "reports/model_card.md",
            "leakage_audit": "reports/leakage_audit.md",
            "proxy_risk_review": "reports/fairness_proxy_analysis.md",
            "governance_checklist": "reports/governance_checklist.md",
            "production_status": "Portfolio prototype; not production-approved.",
        },
    }


def markdown_table(rows: list[tuple[str, Any]]) -> str:
    """Render two-column markdown table."""
    table = ["| field | value |", "| --- | --- |"]
    for key, value in rows:
        table.append(f"| {key} | `{value}` |")
    return "\n".join(table)


def write_registry_docs(entry: dict[str, Any]) -> None:
    """Write model registry metadata as JSON and Markdown."""
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    REGISTRY_JSON_PATH.write_text(
        json.dumps(entry, indent=2, sort_keys=True), encoding="utf-8"
    )

    validation = entry.get("validation_metrics", {})
    test = entry.get("test_metrics", {})
    mlflow_status = entry.get("mlflow", {})
    md = "\n".join(
        [
            "# Model Registry",
            "",
            "This document is a lightweight model registry-style record for the "
            "saved FinSight final model. It is generated from existing artifacts "
            "and does not retrain the model.",
            "",
            "## Registry Entry",
            "",
            markdown_table(
                [
                    ("model_name", entry["model_name"]),
                    ("model_version", entry["model_version"]),
                    ("model_stage", entry["model_stage"]),
                    ("model_type", entry["model_type"]),
                    ("selection_metric", entry["selection_metric"]),
                    ("threshold_strategy", entry["threshold_strategy"]),
                    ("threshold", entry["threshold"]),
                    ("top_k", entry["top_k"]),
                    ("rows_loaded", entry["rows_loaded"]),
                    ("feature_count", entry["feature_count"]),
                    ("artifact_path", entry["artifact_path"]),
                ]
            ),
            "",
            "## Validation Metrics",
            "",
            markdown_table(
                [
                    ("roc_auc", validation.get("roc_auc")),
                    ("pr_auc", validation.get("pr_auc")),
                    ("precision", validation.get("precision")),
                    ("recall", validation.get("recall")),
                    ("f1_score", validation.get("f1_score")),
                    ("recall_at_top_10pct", validation.get("recall_at_top_10pct")),
                    ("ks_statistic", validation.get("ks_statistic")),
                ]
            ),
            "",
            "## Test Metrics",
            "",
            markdown_table(
                [
                    ("roc_auc", test.get("roc_auc")),
                    ("pr_auc", test.get("pr_auc")),
                    ("precision", test.get("precision")),
                    ("recall", test.get("recall")),
                    ("f1_score", test.get("f1_score")),
                    ("recall_at_top_10pct", test.get("recall_at_top_10pct")),
                    ("ks_statistic", test.get("ks_statistic")),
                ]
            ),
            "",
            "## MLflow Status",
            "",
            markdown_table(
                [
                    ("status", mlflow_status.get("status")),
                    ("tracking_uri", mlflow_status.get("tracking_uri")),
                    ("experiment_name", mlflow_status.get("experiment_name")),
                    ("run_id", mlflow_status.get("run_id")),
                ]
            ),
            "",
            "## Governance References",
            "",
            "- `reports/model_card.md`",
            "- `reports/leakage_audit.md`",
            "- `reports/fairness_proxy_analysis.md`",
            "- `reports/governance_checklist.md`",
            "",
            "## Production Status",
            "",
            "This is a portfolio-ready model registry record. A real production "
            "registry would additionally require artifact storage controls, model "
            "approval workflow, deployment environment metadata, rollback links, "
            "monitoring ownership, and compliance sign-off.",
            "",
        ]
    )
    REGISTRY_MD_PATH.write_text(md, encoding="utf-8")


def try_log_to_mlflow(
    metrics: dict[str, Any],
    tracking_uri: str,
    experiment_name: str,
    run_name: str,
    skip_mlflow: bool = False,
) -> dict[str, Any]:
    """Log existing metrics and artifacts to MLflow when available."""
    if skip_mlflow:
        return {
            "status": "skipped_by_user",
            "tracking_uri": tracking_uri,
            "experiment_name": experiment_name,
            "run_id": None,
        }

    try:
        import mlflow
    except ModuleNotFoundError:
        return {
            "status": "mlflow_not_installed",
            "tracking_uri": tracking_uri,
            "experiment_name": experiment_name,
            "run_id": None,
        }

    try:
        if tracking_uri.startswith("sqlite:///"):
            db_path = Path(tracking_uri.removeprefix("sqlite:///"))
            db_path.parent.mkdir(parents=True, exist_ok=True)

        mlflow.set_tracking_uri(tracking_uri)
        mlflow.set_experiment(experiment_name)
        with mlflow.start_run(run_name=run_name) as run:
            mlflow.set_tag("project", "FinSight")
            mlflow.set_tag("model_stage", "portfolio_ready_not_production_approved")
            mlflow.set_tag("no_retraining", "true")
            mlflow.log_param("model_type", metrics.get("model_type"))
            mlflow.log_param("selection_metric", metrics.get("selection_metric"))
            mlflow.log_param("threshold_strategy", metrics.get("threshold_strategy"))
            mlflow.log_param("feature_count", metrics.get("feature_count"))
            mlflow.log_param("rows_loaded", metrics.get("rows_loaded"))
            for param_name, value in metrics.get("best_params", {}).items():
                mlflow.log_param(f"best_{param_name}", value)
            for metric_name, value in flatten_metrics(metrics).items():
                mlflow.log_metric(metric_name, value)
            for artifact_path in ARTIFACT_PATHS:
                if artifact_path.exists():
                    mlflow.log_artifact(
                        artifact_path.as_posix(), artifact_path="reports"
                    )
            return {
                "status": "logged",
                "tracking_uri": tracking_uri,
                "experiment_name": experiment_name,
                "run_id": run.info.run_id,
            }
    except Exception as exc:
        return {
            "status": "mlflow_logging_failed",
            "tracking_uri": tracking_uri,
            "experiment_name": experiment_name,
            "run_id": None,
            "error": f"{type(exc).__name__}: {exc}",
        }


def write_mlflow_summary(entry: dict[str, Any]) -> None:
    """Write human-readable MLflow experiment summary."""
    mlflow_status = entry["mlflow"]
    status = mlflow_status.get("status")
    summary = [
        "# MLflow Experiment Summary",
        "",
        "This report documents MLflow tracking for the existing FinSight final "
        "model artifacts. The script does not train or retrain any model.",
        "",
        "## Status",
        "",
        markdown_table(
            [
                ("status", status),
                ("tracking_uri", mlflow_status.get("tracking_uri")),
                ("experiment_name", mlflow_status.get("experiment_name")),
                ("run_id", mlflow_status.get("run_id")),
            ]
        ),
        "",
        "## Logged Content",
        "",
        "- Final model parameters from `reports/final_model_metrics.json`",
        "- Validation and test classification metrics",
        "- Validation and test Brier scores",
        "- Final model report, calibration report, cross-validation summary, "
        "business impact summary, explainability summary, fairness/proxy-risk "
        "analysis, leakage audit, and model card when present",
        "",
        "## How To Run",
        "",
        "```bash",
        "python src/models/mlflow_tracking.py",
        "```",
        "",
        "Open the local MLflow UI after logging:",
        "",
        "```bash",
        "mlflow ui --backend-store-uri sqlite:///mlruns/mlflow.db",
        "```",
        "",
    ]
    if status == "mlflow_not_installed":
        summary.extend(
            [
                "## Local Environment Note",
                "",
                "MLflow is not installed in the current environment, so the script "
                "wrote registry documentation but did not create an MLflow run. "
                "Install project requirements and rerun the command to create the "
                "local SQLite `mlruns/mlflow.db` tracking store.",
                "",
            ]
        )
    if status == "mlflow_logging_failed":
        summary.extend(
            [
                "## MLflow Logging Error",
                "",
                "MLflow is installed, but the local logging attempt failed. The "
                "script still wrote registry documentation so the project remains "
                "reviewable.",
                "",
                f"- Error: `{mlflow_status.get('error')}`",
                "",
            ]
        )
    summary.extend(
        [
            "## Registry Outputs",
            "",
            "- `reports/model_registry.json`",
            "- `reports/model_registry.md`",
            "- `reports/mlflow_experiment_summary.md`",
            "",
            "## Production Interpretation",
            "",
            "This adds experiment tracking and registry-style documentation for "
            "portfolio reproducibility. A real production model registry would "
            "also include approval stages, access control, artifact retention, "
            "deployment links, rollback metadata, and model owner sign-off.",
            "",
        ]
    )
    MLFLOW_SUMMARY_PATH.write_text("\n".join(summary), encoding="utf-8")


def run(
    tracking_uri: str = MLFLOW_TRACKING_URI,
    experiment_name: str = EXPERIMENT_NAME,
    run_name: str = RUN_NAME,
    skip_mlflow: bool = False,
) -> dict[str, Any]:
    """Create MLflow run when possible and write registry docs."""
    metrics = load_metrics()
    mlflow_status = try_log_to_mlflow(
        metrics=metrics,
        tracking_uri=tracking_uri,
        experiment_name=experiment_name,
        run_name=run_name,
        skip_mlflow=skip_mlflow,
    )
    entry = registry_entry(metrics, mlflow_status)
    write_registry_docs(entry)
    write_mlflow_summary(entry)
    return entry


def main() -> None:
    """CLI entry point."""
    args = parse_args()
    entry = run(
        tracking_uri=args.tracking_uri,
        experiment_name=args.experiment_name,
        run_name=args.run_name,
        skip_mlflow=args.skip_mlflow,
    )
    print("MLflow tracking documentation complete.")
    print(f"MLflow status: {entry['mlflow']['status']}")
    print(f"Registry JSON saved to: {REGISTRY_JSON_PATH}")
    print(f"Registry report saved to: {REGISTRY_MD_PATH}")
    print(f"MLflow summary saved to: {MLFLOW_SUMMARY_PATH}")


if __name__ == "__main__":
    main()
